INSERT INTO "JobOption" ("id", "type", "label", "value", "description", "sortOrder", "active", "updatedAt") VALUES
('jobopt_location_ahmedabad', 'LOCATION', 'Ahmedabad', 'Ahmedabad, Gujarat, India', 'Major Indian hiring city', 6, true, CURRENT_TIMESTAMP),
('jobopt_location_surat', 'LOCATION', 'Surat', 'Surat, Gujarat, India', 'Major Indian hiring city', 7, true, CURRENT_TIMESTAMP),
('jobopt_location_vadodara', 'LOCATION', 'Vadodara', 'Vadodara, Gujarat, India', 'Major Indian hiring city', 8, true, CURRENT_TIMESTAMP),
('jobopt_location_rajkot', 'LOCATION', 'Rajkot', 'Rajkot, Gujarat, India', 'Major Indian hiring city', 9, true, CURRENT_TIMESTAMP),
('jobopt_location_bhavnagar', 'LOCATION', 'Bhavnagar', 'Bhavnagar, Gujarat, India', 'Major Indian hiring city', 10, true, CURRENT_TIMESTAMP),
('jobopt_location_jamnagar', 'LOCATION', 'Jamnagar', 'Jamnagar, Gujarat, India', 'Major Indian hiring city', 11, true, CURRENT_TIMESTAMP),
('jobopt_location_gandhinagar', 'LOCATION', 'Gandhinagar', 'Gandhinagar, Gujarat, India', 'Major Indian hiring city', 12, true, CURRENT_TIMESTAMP),
('jobopt_location_anand', 'LOCATION', 'Anand', 'Anand, Gujarat, India', 'Major Indian hiring city', 13, true, CURRENT_TIMESTAMP),
('jobopt_location_bharuch', 'LOCATION', 'Bharuch', 'Bharuch, Gujarat, India', 'Major Indian hiring city', 14, true, CURRENT_TIMESTAMP),
('jobopt_location_vapi', 'LOCATION', 'Vapi', 'Vapi, Gujarat, India', 'Major Indian hiring city', 15, true, CURRENT_TIMESTAMP),
('jobopt_location_nashik', 'LOCATION', 'Nashik', 'Nashik, Maharashtra, India', 'Major Indian hiring city', 16, true, CURRENT_TIMESTAMP),
('jobopt_location_nagpur', 'LOCATION', 'Nagpur', 'Nagpur, Maharashtra, India', 'Major Indian hiring city', 17, true, CURRENT_TIMESTAMP),
('jobopt_location_thane', 'LOCATION', 'Thane', 'Thane, Maharashtra, India', 'Major Indian hiring city', 18, true, CURRENT_TIMESTAMP),
('jobopt_location_navi_mumbai', 'LOCATION', 'Navi Mumbai', 'Navi Mumbai, Maharashtra, India', 'Major Indian hiring city', 19, true, CURRENT_TIMESTAMP),
('jobopt_location_aurangabad', 'LOCATION', 'Aurangabad', 'Aurangabad, Maharashtra, India', 'Major Indian hiring city', 20, true, CURRENT_TIMESTAMP),
('jobopt_location_solapur', 'LOCATION', 'Solapur', 'Solapur, Maharashtra, India', 'Major Indian hiring city', 21, true, CURRENT_TIMESTAMP),
('jobopt_location_kolhapur', 'LOCATION', 'Kolhapur', 'Kolhapur, Maharashtra, India', 'Major Indian hiring city', 22, true, CURRENT_TIMESTAMP),
('jobopt_location_amravati', 'LOCATION', 'Amravati', 'Amravati, Maharashtra, India', 'Major Indian hiring city', 23, true, CURRENT_TIMESTAMP),
('jobopt_location_jalgaon', 'LOCATION', 'Jalgaon', 'Jalgaon, Maharashtra, India', 'Major Indian hiring city', 24, true, CURRENT_TIMESTAMP),
('jobopt_location_ahmednagar', 'LOCATION', 'Ahmednagar', 'Ahmednagar, Maharashtra, India', 'Major Indian hiring city', 25, true, CURRENT_TIMESTAMP),
('jobopt_location_chennai', 'LOCATION', 'Chennai', 'Chennai, Tamil Nadu, India', 'Major Indian hiring city', 26, true, CURRENT_TIMESTAMP),
('jobopt_location_coimbatore', 'LOCATION', 'Coimbatore', 'Coimbatore, Tamil Nadu, India', 'Major Indian hiring city', 27, true, CURRENT_TIMESTAMP),
('jobopt_location_madurai', 'LOCATION', 'Madurai', 'Madurai, Tamil Nadu, India', 'Major Indian hiring city', 28, true, CURRENT_TIMESTAMP),
('jobopt_location_tiruchirappalli', 'LOCATION', 'Tiruchirappalli', 'Tiruchirappalli, Tamil Nadu, India', 'Major Indian hiring city', 29, true, CURRENT_TIMESTAMP),
('jobopt_location_salem', 'LOCATION', 'Salem', 'Salem, Tamil Nadu, India', 'Major Indian hiring city', 30, true, CURRENT_TIMESTAMP),
('jobopt_location_tiruppur', 'LOCATION', 'Tiruppur', 'Tiruppur, Tamil Nadu, India', 'Major Indian hiring city', 31, true, CURRENT_TIMESTAMP),
('jobopt_location_erode', 'LOCATION', 'Erode', 'Erode, Tamil Nadu, India', 'Major Indian hiring city', 32, true, CURRENT_TIMESTAMP),
('jobopt_location_vellore', 'LOCATION', 'Vellore', 'Vellore, Tamil Nadu, India', 'Major Indian hiring city', 33, true, CURRENT_TIMESTAMP),
('jobopt_location_mysuru', 'LOCATION', 'Mysuru', 'Mysuru, Karnataka, India', 'Major Indian hiring city', 34, true, CURRENT_TIMESTAMP),
('jobopt_location_mangaluru', 'LOCATION', 'Mangaluru', 'Mangaluru, Karnataka, India', 'Major Indian hiring city', 35, true, CURRENT_TIMESTAMP),
('jobopt_location_hubballi', 'LOCATION', 'Hubballi', 'Hubballi, Karnataka, India', 'Major Indian hiring city', 36, true, CURRENT_TIMESTAMP),
('jobopt_location_belagavi', 'LOCATION', 'Belagavi', 'Belagavi, Karnataka, India', 'Major Indian hiring city', 37, true, CURRENT_TIMESTAMP),
('jobopt_location_davanagere', 'LOCATION', 'Davanagere', 'Davanagere, Karnataka, India', 'Major Indian hiring city', 38, true, CURRENT_TIMESTAMP),
('jobopt_location_shivamogga', 'LOCATION', 'Shivamogga', 'Shivamogga, Karnataka, India', 'Major Indian hiring city', 39, true, CURRENT_TIMESTAMP),
('jobopt_location_ballari', 'LOCATION', 'Ballari', 'Ballari, Karnataka, India', 'Major Indian hiring city', 40, true, CURRENT_TIMESTAMP),
('jobopt_location_kochi', 'LOCATION', 'Kochi', 'Kochi, Kerala, India', 'Major Indian hiring city', 41, true, CURRENT_TIMESTAMP),
('jobopt_location_thiruvananthapuram', 'LOCATION', 'Thiruvananthapuram', 'Thiruvananthapuram, Kerala, India', 'Major Indian hiring city', 42, true, CURRENT_TIMESTAMP),
('jobopt_location_kozhikode', 'LOCATION', 'Kozhikode', 'Kozhikode, Kerala, India', 'Major Indian hiring city', 43, true, CURRENT_TIMESTAMP),
('jobopt_location_thrissur', 'LOCATION', 'Thrissur', 'Thrissur, Kerala, India', 'Major Indian hiring city', 44, true, CURRENT_TIMESTAMP),
('jobopt_location_kollam', 'LOCATION', 'Kollam', 'Kollam, Kerala, India', 'Major Indian hiring city', 45, true, CURRENT_TIMESTAMP),
('jobopt_location_visakhapatnam', 'LOCATION', 'Visakhapatnam', 'Visakhapatnam, Andhra Pradesh, India', 'Major Indian hiring city', 46, true, CURRENT_TIMESTAMP),
('jobopt_location_vijayawada', 'LOCATION', 'Vijayawada', 'Vijayawada, Andhra Pradesh, India', 'Major Indian hiring city', 47, true, CURRENT_TIMESTAMP),
('jobopt_location_guntur', 'LOCATION', 'Guntur', 'Guntur, Andhra Pradesh, India', 'Major Indian hiring city', 48, true, CURRENT_TIMESTAMP),
('jobopt_location_tirupati', 'LOCATION', 'Tirupati', 'Tirupati, Andhra Pradesh, India', 'Major Indian hiring city', 49, true, CURRENT_TIMESTAMP),
('jobopt_location_nellore', 'LOCATION', 'Nellore', 'Nellore, Andhra Pradesh, India', 'Major Indian hiring city', 50, true, CURRENT_TIMESTAMP),
('jobopt_location_kurnool', 'LOCATION', 'Kurnool', 'Kurnool, Andhra Pradesh, India', 'Major Indian hiring city', 51, true, CURRENT_TIMESTAMP),
('jobopt_location_warangal', 'LOCATION', 'Warangal', 'Warangal, Telangana, India', 'Major Indian hiring city', 52, true, CURRENT_TIMESTAMP),
('jobopt_location_nizamabad', 'LOCATION', 'Nizamabad', 'Nizamabad, Telangana, India', 'Major Indian hiring city', 53, true, CURRENT_TIMESTAMP),
('jobopt_location_karimnagar', 'LOCATION', 'Karimnagar', 'Karimnagar, Telangana, India', 'Major Indian hiring city', 54, true, CURRENT_TIMESTAMP),
('jobopt_location_khammam', 'LOCATION', 'Khammam', 'Khammam, Telangana, India', 'Major Indian hiring city', 55, true, CURRENT_TIMESTAMP),
('jobopt_location_kolkata', 'LOCATION', 'Kolkata', 'Kolkata, West Bengal, India', 'Major Indian hiring city', 56, true, CURRENT_TIMESTAMP),
('jobopt_location_howrah', 'LOCATION', 'Howrah', 'Howrah, West Bengal, India', 'Major Indian hiring city', 57, true, CURRENT_TIMESTAMP),
('jobopt_location_durgapur', 'LOCATION', 'Durgapur', 'Durgapur, West Bengal, India', 'Major Indian hiring city', 58, true, CURRENT_TIMESTAMP),
('jobopt_location_asansol', 'LOCATION', 'Asansol', 'Asansol, West Bengal, India', 'Major Indian hiring city', 59, true, CURRENT_TIMESTAMP),
('jobopt_location_siliguri', 'LOCATION', 'Siliguri', 'Siliguri, West Bengal, India', 'Major Indian hiring city', 60, true, CURRENT_TIMESTAMP),
('jobopt_location_bhubaneswar', 'LOCATION', 'Bhubaneswar', 'Bhubaneswar, Odisha, India', 'Major Indian hiring city', 61, true, CURRENT_TIMESTAMP),
('jobopt_location_cuttack', 'LOCATION', 'Cuttack', 'Cuttack, Odisha, India', 'Major Indian hiring city', 62, true, CURRENT_TIMESTAMP),
('jobopt_location_rourkela', 'LOCATION', 'Rourkela', 'Rourkela, Odisha, India', 'Major Indian hiring city', 63, true, CURRENT_TIMESTAMP),
('jobopt_location_sambalpur', 'LOCATION', 'Sambalpur', 'Sambalpur, Odisha, India', 'Major Indian hiring city', 64, true, CURRENT_TIMESTAMP),
('jobopt_location_balasore', 'LOCATION', 'Balasore', 'Balasore, Odisha, India', 'Major Indian hiring city', 65, true, CURRENT_TIMESTAMP),
('jobopt_location_ranchi', 'LOCATION', 'Ranchi', 'Ranchi, Jharkhand, India', 'Major Indian hiring city', 66, true, CURRENT_TIMESTAMP),
('jobopt_location_jamshedpur', 'LOCATION', 'Jamshedpur', 'Jamshedpur, Jharkhand, India', 'Major Indian hiring city', 67, true, CURRENT_TIMESTAMP),
('jobopt_location_dhanbad', 'LOCATION', 'Dhanbad', 'Dhanbad, Jharkhand, India', 'Major Indian hiring city', 68, true, CURRENT_TIMESTAMP),
('jobopt_location_bokaro', 'LOCATION', 'Bokaro', 'Bokaro, Jharkhand, India', 'Major Indian hiring city', 69, true, CURRENT_TIMESTAMP),
('jobopt_location_patna', 'LOCATION', 'Patna', 'Patna, Bihar, India', 'Major Indian hiring city', 70, true, CURRENT_TIMESTAMP),
('jobopt_location_gaya', 'LOCATION', 'Gaya', 'Gaya, Bihar, India', 'Major Indian hiring city', 71, true, CURRENT_TIMESTAMP),
('jobopt_location_bhagalpur', 'LOCATION', 'Bhagalpur', 'Bhagalpur, Bihar, India', 'Major Indian hiring city', 72, true, CURRENT_TIMESTAMP),
('jobopt_location_muzaffarpur', 'LOCATION', 'Muzaffarpur', 'Muzaffarpur, Bihar, India', 'Major Indian hiring city', 73, true, CURRENT_TIMESTAMP),
('jobopt_location_lucknow', 'LOCATION', 'Lucknow', 'Lucknow, Uttar Pradesh, India', 'Major Indian hiring city', 74, true, CURRENT_TIMESTAMP),
('jobopt_location_kanpur', 'LOCATION', 'Kanpur', 'Kanpur, Uttar Pradesh, India', 'Major Indian hiring city', 75, true, CURRENT_TIMESTAMP),
('jobopt_location_noida', 'LOCATION', 'Noida', 'Noida, Uttar Pradesh, India', 'Major Indian hiring city', 76, true, CURRENT_TIMESTAMP),
('jobopt_location_ghaziabad', 'LOCATION', 'Ghaziabad', 'Ghaziabad, Uttar Pradesh, India', 'Major Indian hiring city', 77, true, CURRENT_TIMESTAMP),
('jobopt_location_agra', 'LOCATION', 'Agra', 'Agra, Uttar Pradesh, India', 'Major Indian hiring city', 78, true, CURRENT_TIMESTAMP),
('jobopt_location_varanasi', 'LOCATION', 'Varanasi', 'Varanasi, Uttar Pradesh, India', 'Major Indian hiring city', 79, true, CURRENT_TIMESTAMP),
('jobopt_location_prayagraj', 'LOCATION', 'Prayagraj', 'Prayagraj, Uttar Pradesh, India', 'Major Indian hiring city', 80, true, CURRENT_TIMESTAMP),
('jobopt_location_meerut', 'LOCATION', 'Meerut', 'Meerut, Uttar Pradesh, India', 'Major Indian hiring city', 81, true, CURRENT_TIMESTAMP),
('jobopt_location_bareilly', 'LOCATION', 'Bareilly', 'Bareilly, Uttar Pradesh, India', 'Major Indian hiring city', 82, true, CURRENT_TIMESTAMP),
('jobopt_location_aligarh', 'LOCATION', 'Aligarh', 'Aligarh, Uttar Pradesh, India', 'Major Indian hiring city', 83, true, CURRENT_TIMESTAMP),
('jobopt_location_gorakhpur', 'LOCATION', 'Gorakhpur', 'Gorakhpur, Uttar Pradesh, India', 'Major Indian hiring city', 84, true, CURRENT_TIMESTAMP),
('jobopt_location_jaipur', 'LOCATION', 'Jaipur', 'Jaipur, Rajasthan, India', 'Major Indian hiring city', 85, true, CURRENT_TIMESTAMP),
('jobopt_location_jodhpur', 'LOCATION', 'Jodhpur', 'Jodhpur, Rajasthan, India', 'Major Indian hiring city', 86, true, CURRENT_TIMESTAMP),
('jobopt_location_kota', 'LOCATION', 'Kota', 'Kota, Rajasthan, India', 'Major Indian hiring city', 87, true, CURRENT_TIMESTAMP),
('jobopt_location_udaipur', 'LOCATION', 'Udaipur', 'Udaipur, Rajasthan, India', 'Major Indian hiring city', 88, true, CURRENT_TIMESTAMP),
('jobopt_location_ajmer', 'LOCATION', 'Ajmer', 'Ajmer, Rajasthan, India', 'Major Indian hiring city', 89, true, CURRENT_TIMESTAMP),
('jobopt_location_bikaner', 'LOCATION', 'Bikaner', 'Bikaner, Rajasthan, India', 'Major Indian hiring city', 90, true, CURRENT_TIMESTAMP),
('jobopt_location_indore', 'LOCATION', 'Indore', 'Indore, Madhya Pradesh, India', 'Major Indian hiring city', 91, true, CURRENT_TIMESTAMP),
('jobopt_location_bhopal', 'LOCATION', 'Bhopal', 'Bhopal, Madhya Pradesh, India', 'Major Indian hiring city', 92, true, CURRENT_TIMESTAMP),
('jobopt_location_gwalior', 'LOCATION', 'Gwalior', 'Gwalior, Madhya Pradesh, India', 'Major Indian hiring city', 93, true, CURRENT_TIMESTAMP),
('jobopt_location_jabalpur', 'LOCATION', 'Jabalpur', 'Jabalpur, Madhya Pradesh, India', 'Major Indian hiring city', 94, true, CURRENT_TIMESTAMP),
('jobopt_location_ujjain', 'LOCATION', 'Ujjain', 'Ujjain, Madhya Pradesh, India', 'Major Indian hiring city', 95, true, CURRENT_TIMESTAMP),
('jobopt_location_raipur', 'LOCATION', 'Raipur', 'Raipur, Chhattisgarh, India', 'Major Indian hiring city', 96, true, CURRENT_TIMESTAMP),
('jobopt_location_bhilai', 'LOCATION', 'Bhilai', 'Bhilai, Chhattisgarh, India', 'Major Indian hiring city', 97, true, CURRENT_TIMESTAMP),
('jobopt_location_bilaspur', 'LOCATION', 'Bilaspur', 'Bilaspur, Chhattisgarh, India', 'Major Indian hiring city', 98, true, CURRENT_TIMESTAMP),
('jobopt_location_chandigarh', 'LOCATION', 'Chandigarh', 'Chandigarh, Chandigarh, India', 'Major Indian hiring city', 99, true, CURRENT_TIMESTAMP),
('jobopt_location_ludhiana', 'LOCATION', 'Ludhiana', 'Ludhiana, Punjab, India', 'Major Indian hiring city', 100, true, CURRENT_TIMESTAMP),
('jobopt_location_amritsar', 'LOCATION', 'Amritsar', 'Amritsar, Punjab, India', 'Major Indian hiring city', 101, true, CURRENT_TIMESTAMP),
('jobopt_location_jalandhar', 'LOCATION', 'Jalandhar', 'Jalandhar, Punjab, India', 'Major Indian hiring city', 102, true, CURRENT_TIMESTAMP),
('jobopt_location_patiala', 'LOCATION', 'Patiala', 'Patiala, Punjab, India', 'Major Indian hiring city', 103, true, CURRENT_TIMESTAMP),
('jobopt_location_gurugram', 'LOCATION', 'Gurugram', 'Gurugram, Haryana, India', 'Major Indian hiring city', 104, true, CURRENT_TIMESTAMP),
('jobopt_location_faridabad', 'LOCATION', 'Faridabad', 'Faridabad, Haryana, India', 'Major Indian hiring city', 105, true, CURRENT_TIMESTAMP),
('jobopt_location_panipat', 'LOCATION', 'Panipat', 'Panipat, Haryana, India', 'Major Indian hiring city', 106, true, CURRENT_TIMESTAMP),
('jobopt_location_ambala', 'LOCATION', 'Ambala', 'Ambala, Haryana, India', 'Major Indian hiring city', 107, true, CURRENT_TIMESTAMP),
('jobopt_location_dehradun', 'LOCATION', 'Dehradun', 'Dehradun, Uttarakhand, India', 'Major Indian hiring city', 108, true, CURRENT_TIMESTAMP),
('jobopt_location_haridwar', 'LOCATION', 'Haridwar', 'Haridwar, Uttarakhand, India', 'Major Indian hiring city', 109, true, CURRENT_TIMESTAMP),
('jobopt_location_roorkee', 'LOCATION', 'Roorkee', 'Roorkee, Uttarakhand, India', 'Major Indian hiring city', 110, true, CURRENT_TIMESTAMP),
('jobopt_location_shimla', 'LOCATION', 'Shimla', 'Shimla, Himachal Pradesh, India', 'Major Indian hiring city', 111, true, CURRENT_TIMESTAMP),
('jobopt_location_jammu', 'LOCATION', 'Jammu', 'Jammu, Jammu and Kashmir, India', 'Major Indian hiring city', 112, true, CURRENT_TIMESTAMP),
('jobopt_location_srinagar', 'LOCATION', 'Srinagar', 'Srinagar, Jammu and Kashmir, India', 'Major Indian hiring city', 113, true, CURRENT_TIMESTAMP),
('jobopt_location_guwahati', 'LOCATION', 'Guwahati', 'Guwahati, Assam, India', 'Major Indian hiring city', 114, true, CURRENT_TIMESTAMP),
('jobopt_location_dibrugarh', 'LOCATION', 'Dibrugarh', 'Dibrugarh, Assam, India', 'Major Indian hiring city', 115, true, CURRENT_TIMESTAMP),
('jobopt_location_shillong', 'LOCATION', 'Shillong', 'Shillong, Meghalaya, India', 'Major Indian hiring city', 116, true, CURRENT_TIMESTAMP),
('jobopt_location_imphal', 'LOCATION', 'Imphal', 'Imphal, Manipur, India', 'Major Indian hiring city', 117, true, CURRENT_TIMESTAMP),
('jobopt_location_aizawl', 'LOCATION', 'Aizawl', 'Aizawl, Mizoram, India', 'Major Indian hiring city', 118, true, CURRENT_TIMESTAMP),
('jobopt_location_agartala', 'LOCATION', 'Agartala', 'Agartala, Tripura, India', 'Major Indian hiring city', 119, true, CURRENT_TIMESTAMP),
('jobopt_location_gangtok', 'LOCATION', 'Gangtok', 'Gangtok, Sikkim, India', 'Major Indian hiring city', 120, true, CURRENT_TIMESTAMP),
('jobopt_location_itanagar', 'LOCATION', 'Itanagar', 'Itanagar, Arunachal Pradesh, India', 'Major Indian hiring city', 121, true, CURRENT_TIMESTAMP),
('jobopt_location_panaji', 'LOCATION', 'Panaji', 'Panaji, Goa, India', 'Major Indian hiring city', 122, true, CURRENT_TIMESTAMP),
('jobopt_location_margao', 'LOCATION', 'Margao', 'Margao, Goa, India', 'Major Indian hiring city', 123, true, CURRENT_TIMESTAMP),
('jobopt_location_pondicherry', 'LOCATION', 'Puducherry', 'Puducherry, Puducherry, India', 'Major Indian hiring city', 124, true, CURRENT_TIMESTAMP)
ON CONFLICT ("type", "value") DO NOTHING;
